package ims

import (
	"context"
	"math"
	"net"
	"testing"
	"time"
)

func TestRTPMediaCarriesPCMOverPCMA(t *testing.T) {
	left, err := newRTPMedia(net.IPv4(127, 0, 0, 1), nil)
	if err != nil {
		t.Fatal(err)
	}
	defer left.Close()
	right, err := newRTPMedia(net.IPv4(127, 0, 0, 1), nil)
	if err != nil {
		t.Fatal(err)
	}
	defer right.Close()
	if err := left.configureRemote(right.offerSDP(net.IPv4(127, 0, 0, 1))); err != nil {
		t.Fatal(err)
	}
	if err := right.configureRemote(left.answerSDP(net.IPv4(127, 0, 0, 1))); err != nil {
		t.Fatal(err)
	}
	want := make([]int16, rtpPacketSamples)
	for index := range want {
		want[index] = int16(9000 * math.Sin(float64(index)*2*math.Pi/40))
	}
	if err := left.WritePCM(want); err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	// The uplink now runs on a fixed 20 ms cadence and fills unqueued slots
	// with silence, so the tone may be preceded by silent packets.
	got, err := readVoicedFrame(ctx, right)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != len(want) {
		t.Fatalf("received %d samples, want %d", len(got), len(want))
	}
	for index := range got {
		if difference := math.Abs(float64(got[index]) - float64(want[index])); difference > 700 {
			t.Fatalf("sample %d difference %.0f exceeds G.711 tolerance", index, difference)
		}
	}
}

func TestParseAudioSDPRejectsMissingEndpoint(t *testing.T) {
	if _, _, _, _, err := parseAudioSDP([]byte("v=0\r\nm=audio 0 RTP/AVP 8\r\n")); err == nil {
		t.Fatal("expected unusable SDP error")
	}
}

// readVoicedFrame skips the silence the transmit pump emits between queued
// audio and returns the first frame carrying signal.
func readVoicedFrame(ctx context.Context, media *rtpMedia) ([]int16, error) {
	for {
		samples, err := media.ReadPCM(ctx)
		if err != nil {
			return nil, err
		}
		for _, sample := range samples {
			if sample > 64 || sample < -64 {
				return samples, nil
			}
		}
	}
}

// The IMS access gateway tears a call down when RTP stops arriving, so the
// uplink must keep running when no browser is attached and nothing has been
// queued. Before the transmit pump existed, WritePCM was the only thing that
// ever sent a packet and an unattended call went silent on the wire.
func TestRTPMediaSendsSilenceWithoutQueuedAudio(t *testing.T) {
	sender, err := newRTPMedia(net.IPv4(127, 0, 0, 1), nil)
	if err != nil {
		t.Fatal(err)
	}
	defer sender.Close()
	receiver, err := newRTPMedia(net.IPv4(127, 0, 0, 1), nil)
	if err != nil {
		t.Fatal(err)
	}
	defer receiver.Close()
	if err := sender.configureRemote(receiver.offerSDP(net.IPv4(127, 0, 0, 1))); err != nil {
		t.Fatal(err)
	}
	if err := receiver.configureRemote(sender.answerSDP(net.IPv4(127, 0, 0, 1))); err != nil {
		t.Fatal(err)
	}

	// Nothing is ever written to `sender`; every packet below is generated by
	// the pump alone.
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	for received := 0; received < 3; received++ {
		samples, err := receiver.ReadPCM(ctx)
		if err != nil {
			t.Fatalf("packet %d: %v", received, err)
		}
		if len(samples) != rtpPacketSamples {
			t.Fatalf("packet %d carried %d samples, want %d", received, len(samples), rtpPacketSamples)
		}
		for index, sample := range samples {
			if sample > 64 || sample < -64 {
				t.Fatalf("packet %d sample %d is %d, want silence", received, index, sample)
			}
		}
	}
}
